/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Announcements {
  body: string;
  createdAt: Generated<Date>;
  createdBy: number;
  endsAt: Date;
  id: Generated<number>;
  isActive: Generated<boolean>;
  startsAt: Date;
  title: string;
  type: Generated<"banner" | "popup">;
  updatedAt: Date;
}

export interface AttemptAnswers {
  answeredAt: Generated<Date>;
  attemptId: number;
  id: Generated<number>;
  isCorrect: Generated<boolean | null>;
  marksAwarded: Generated<Decimal>;
  questionId: number;
  selectedOption: Generated<"A" | "B" | "C" | "D" | null>;
}

export interface AuditLogs {
  action: string;
  adminId: number;
  createdAt: Generated<Date>;
  id: Generated<number>;
  metadata: Generated<string | null>;
  targetId: Generated<number | null>;
  targetType: string;
}

export interface Bookmarks {
  contentId: number;
  contentType: "important_question" | "note";
  createdAt: Generated<Date>;
  id: Generated<number>;
  userId: number;
}

export interface CalendarEvents {
  courseId: Generated<number | null>;
  createdAt: Generated<Date>;
  createdBy: number;
  description: Generated<string | null>;
  endsAt: Date;
  id: Generated<number>;
  isRecurring: Generated<boolean>;
  recurrenceEndDate: Generated<Date | null>;
  recurrenceFrequency: Generated<"daily" | "monthly" | "weekly" | null>;
  startsAt: Date;
  title: string;
  type: Generated<"class" | "exam" | "holiday" | "other">;
  updatedAt: Date;
}

export interface Chapters {
  createdAt: Generated<Date>;
  id: Generated<number>;
  orderIndex: Generated<number>;
  subjectId: number;
  title: string;
  updatedAt: Date;
}

export interface ContactMessages {
  createdAt: Generated<Date>;
  email: string;
  id: Generated<number>;
  message: string;
  name: string;
}

export interface CouponCourses {
  couponId: number;
  courseId: number;
  id: Generated<number>;
}

export interface Coupons {
  code: string;
  createdAt: Generated<Date>;
  createdBy: number;
  discountPercent: number;
  id: Generated<number>;
  isActive: Generated<boolean>;
  maxUses: Generated<number | null>;
  name: string;
  updatedAt: Date;
  usedCount: Generated<number>;
}

export interface Courses {
  coverImageUrl: Generated<string | null>;
  createdAt: Generated<Date>;
  createdBy: number;
  description: string;
  id: Generated<number>;
  isFeatured: Generated<boolean>;
  isPaid: Generated<boolean>;
  isPublished: Generated<boolean>;
  paymentQrImagePath: Generated<string | null>;
  price: Generated<Decimal | null>;
  slug: string;
  title: string;
  updatedAt: Date;
}

export interface Enrollments {
  couponId: Generated<number | null>;
  courseId: number;
  discountedPrice: Generated<Decimal | null>;
  id: Generated<number>;
  paymentProofImagePath: Generated<string | null>;
  phone: string;
  requestedAt: Generated<Date>;
  reviewedAt: Generated<Date | null>;
  reviewedBy: Generated<number | null>;
  status: Generated<"approved" | "pending" | "rejected">;
  updatedAt: Date;
  userId: number;
}

export interface FlashCardProgress {
  flashCardId: number;
  id: Generated<number>;
  isFavorite: Generated<boolean>;
  lastReviewedAt: Generated<Date | null>;
  reviewCount: Generated<number>;
  status: Generated<"difficult" | "known" | "new">;
  userId: number;
}

export interface FlashCards {
  back: string;
  chapterId: number;
  createdAt: Generated<Date>;
  createdBy: number;
  front: string;
  id: Generated<number>;
  orderIndex: Generated<number>;
  updatedAt: Date;
}

export interface GamificationProfiles {
  coins: Generated<number>;
  currentStreak: Generated<number>;
  id: Generated<number>;
  lastActivityDate: Generated<Date | null>;
  longestStreak: Generated<number>;
  updatedAt: Date;
  userId: number;
  xp: Generated<number>;
}

export interface HeroImages {
  createdAt: Generated<Date>;
  id: Generated<number>;
  imagePath: string;
  isEnabled: Generated<boolean>;
  orderIndex: Generated<number>;
  placement: Generated<"dashboard" | "public_home">;
  title: string;
  updatedAt: Date;
}

export interface ImportantQuestions {
  chapterId: number;
  createdAt: Generated<Date>;
  filePath: string;
  id: Generated<number>;
  mimeType: string;
  orderIndex: Generated<number>;
  title: string;
  updatedAt: Date;
  uploadedBy: number;
}

export interface LiveExamAnswers {
  answeredAt: Generated<Date>;
  attemptId: number;
  id: Generated<number>;
  isCorrect: Generated<boolean | null>;
  markedForReview: Generated<boolean>;
  marksAwarded: Generated<Decimal>;
  questionId: number;
  selectedOption: Generated<"A" | "B" | "C" | "D" | null>;
}

export interface LiveExamAttempts {
  id: Generated<number>;
  liveExamId: number;
  score: Generated<Decimal | null>;
  startedAt: Generated<Date>;
  status: Generated<"in_progress" | "submitted">;
  submittedAt: Generated<Date | null>;
  totalMarks: Decimal;
  userId: number;
}

export interface LiveExams {
  courseId: Generated<number | null>;
  createdAt: Generated<Date>;
  createdBy: number;
  endsAt: Date;
  id: Generated<number>;
  questionSetId: number;
  startsAt: Date;
  status: Generated<"cancelled" | "completed" | "live" | "scheduled">;
  title: string;
  updatedAt: Date;
}

export interface Notes {
  chapterId: number;
  createdAt: Generated<Date>;
  filePath: string;
  id: Generated<number>;
  orderIndex: Generated<number>;
  title: string;
  updatedAt: Date;
  uploadedBy: number;
}

export interface Notifications {
  body: Generated<string | null>;
  createdAt: Generated<Date>;
  id: Generated<number>;
  isRead: Generated<boolean>;
  link: Generated<string | null>;
  title: string;
  type: Generated<"error" | "info" | "success" | "warning">;
  userId: number;
}

export interface PasswordResetTokens {
  createdAt: Generated<Date>;
  expiresAt: Date;
  id: Generated<number>;
  tokenHash: string;
  usedAt: Generated<Date | null>;
  userId: number;
}

export interface PracticeAttempts {
  id: Generated<number>;
  questionSetId: number;
  score: Generated<Decimal | null>;
  startedAt: Generated<Date>;
  status: Generated<"in_progress" | "submitted">;
  submittedAt: Generated<Date | null>;
  totalMarks: Decimal;
  userId: number;
}

export interface Questions {
  chapterId: Generated<number | null>;
  correctOption: "A" | "B" | "C" | "D";
  createdAt: Generated<Date>;
  createdBy: number;
  difficulty: Generated<"easy" | "hard" | "medium" | "mixed" | null>;
  explanation: Generated<string | null>;
  id: Generated<number>;
  isActive: Generated<boolean>;
  marks: Generated<Decimal>;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  questionText: string;
  subjectId: Generated<number | null>;
  tags: Generated<string | null>;
  updatedAt: Date;
}

export interface QuestionSetItems {
  id: Generated<number>;
  orderIndex: Generated<number>;
  questionId: number;
  questionSetId: number;
}

export interface QuestionSets {
  chapterId: Generated<number | null>;
  createdAt: Generated<Date>;
  createdBy: number;
  difficulty: Generated<"easy" | "hard" | "medium" | "mixed">;
  estimatedMinutes: Generated<number>;
  id: Generated<number>;
  isPublished: Generated<boolean>;
  negativeMarking: Generated<Decimal>;
  subjectId: Generated<number | null>;
  title: string;
  updatedAt: Date;
}

export interface RefreshTokens {
  createdAt: Generated<Date>;
  deviceType: Generated<string | null>;
  expiresAt: Date;
  id: Generated<number>;
  revokedAt: Generated<Date | null>;
  tokenHash: string;
  userId: number;
}

export interface SiteSettings {
  facebookUrl: Generated<string | null>;
  faviconImagePath: Generated<string | null>;
  id: Generated<number>;
  instagramUrl: Generated<string | null>;
  logoImagePath: Generated<string | null>;
  siteName: Generated<string>;
  themePrimaryColor: Generated<string>;
  themeSecondaryColor: Generated<string>;
  tiktokUrl: Generated<string | null>;
  updatedAt: Date;
  youtubeUrl: Generated<string | null>;
}

export interface StudyTasks {
  createdAt: Generated<Date>;
  dueAt: Date;
  id: Generated<number>;
  isDone: Generated<boolean>;
  notes: Generated<string | null>;
  priority: Generated<"high" | "low" | "medium">;
  title: string;
  updatedAt: Date;
  userId: number;
}

export interface Subjects {
  courseId: Generated<number | null>;
  createdAt: Generated<Date>;
  id: Generated<number>;
  orderIndex: Generated<number>;
  title: string;
  updatedAt: Date;
}

export interface UserBadges {
  badgeKey: string;
  earnedAt: Generated<Date>;
  id: Generated<number>;
  userId: number;
}

export interface Users {
  adminRole: Generated<"admin" | "content_manager" | "instructor" | "moderator" | "super_admin" | null>;
  college: Generated<string | null>;
  createdAt: Generated<Date>;
  email: string;
  id: Generated<number>;
  isActive: Generated<boolean>;
  name: string;
  passwordHash: string;
  phone: Generated<string | null>;
  role: Generated<"admin" | "user">;
  twoFactorEnabled: Generated<boolean>;
  twoFactorSecret: Generated<string | null>;
  updatedAt: Date;
}

export interface DB {
  announcements: Announcements;
  attemptAnswers: AttemptAnswers;
  auditLogs: AuditLogs;
  bookmarks: Bookmarks;
  calendarEvents: CalendarEvents;
  chapters: Chapters;
  contactMessages: ContactMessages;
  couponCourses: CouponCourses;
  coupons: Coupons;
  courses: Courses;
  enrollments: Enrollments;
  flashCardProgress: FlashCardProgress;
  flashCards: FlashCards;
  gamificationProfiles: GamificationProfiles;
  heroImages: HeroImages;
  importantQuestions: ImportantQuestions;
  liveExamAnswers: LiveExamAnswers;
  liveExamAttempts: LiveExamAttempts;
  liveExams: LiveExams;
  notes: Notes;
  notifications: Notifications;
  passwordResetTokens: PasswordResetTokens;
  practiceAttempts: PracticeAttempts;
  questions: Questions;
  questionSetItems: QuestionSetItems;
  questionSets: QuestionSets;
  refreshTokens: RefreshTokens;
  siteSettings: SiteSettings;
  studyTasks: StudyTasks;
  subjects: Subjects;
  userBadges: UserBadges;
  users: Users;
}
